print('Hello test one correct')
print('Now this is some -----------------')
print('TIC-TAC-TOE GAME SAMPLE CODE--BORROWED!!Practice work!!')
#print('different again ---AGAIN')
print('Dealt with lots of merge conflicts , now ready to start!!!')
print('STARTING NOW HURRAY!!!!')